### ISSUE TITLE
代码拉下来 出现下列错误

### ISSUE THREAD

**Issue by nanhupatar** [luoquanquan/learn-cli#1]
![image](https://user-images.githubusercontent.com/27266016/50683684-d8f56d80-104d-11e9-831f-acfce158dcce.png)

**Comment by nanhupatar** [comment]
``` shell
npm install 
```
之后

```shell
learn download
```

可以重现

**Comment by luoquanquan** [comment]
脚手架里直接跑 es6 有点问题, 可以直接下载最新的代码[这个地址](https://github.com/luoquanquan/learn-cli/tree/0.0.5)我把模块方案改成了 commonjs2

详情我在[这里](https://juejin.im/post/5bec24ddf265da61171c4a34#heading-3) 备注啦. 

玩儿的开心 😄

**Comment by nanhupatar** [comment]
好的。认认真真跑了一遍
